# Generated by Django 4.1.6 on 2023-03-02 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='number',
        ),
        migrations.AddField(
            model_name='choice',
            name='choicer',
            field=models.ManyToManyField(blank=True, related_name='choicer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
