# Generated by Django 4.1.6 on 2023-03-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_remove_choice_number_choice_choicer_choice_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='pic',
            field=models.ImageField(default='/media/noimage.png', upload_to='vote/%y/%m'),
        ),
    ]
