# Generated by Django 4.1.6 on 2023-03-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_topic_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='pic',
            field=models.ImageField(default='media/noimage.png', upload_to='vote/%y/%m'),
        ),
    ]
