# Generated by Django 4.1.6 on 2023-03-02 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0005_alter_topic_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choicer',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
