# Generated by Django 4.1.6 on 2023-02-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_reply_pubdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='updated',
            field=models.TextField(default=''),
        ),
    ]
